//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm_test.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class КалиевПрактикаEntities : DbContext
    {
        public КалиевПрактикаEntities()
            : base("name=КалиевПрактикаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Катогория> Катогория { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Производитель> Производитель { get; set; }
        public virtual DbSet<ПунктВыдачи> ПунктВыдачи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<СтатусЗаказа> СтатусЗаказа { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
        public virtual DbSet<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
