//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm_test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Номер_заказа { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public Nullable<int> НомерПункта { get; set; }
        public Nullable<int> НомерПользователя { get; set; }
        public Nullable<int> Код_для_получения { get; set; }
        public Nullable<int> НомерСтатуса { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктВыдачи ПунктВыдачи { get; set; }
        public virtual СтатусЗаказа СтатусЗаказа { get; set; }
        public virtual СоставЗаказа СоставЗаказа { get; set; }
    }
}
