//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm_test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказа
    {
        public int НомерЗаказа { get; set; }
        public string Артикул_заказа { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
