//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm_test.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> НомерПоставщика { get; set; }
        public Nullable<int> НомерПроизводителя { get; set; }
        public Nullable<int> НомерКатегории { get; set; }
        public Nullable<int> Действующая_скидка { get; set; }
        public Nullable<int> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }

        public string Photo
        {
            get
            {
                if (Фото == null)
                    return @"\Photo\picture.png";
                else return "\\Photo\\" + Фото;
            }
        }


        public string color
        {
            get
            {
                if (Действующая_скидка > 15)
                    return "#483D8B";
                if (Кол_во_на_складе == 0)
                    return "Gray";
                
                return null;
            }
        }


        public string Decorations
        {
            get
            {
                if (Действующая_скидка >= 1)
                    return "Strikethrough";
                else return null;
            }
        }

        public string PriceColorNew
        {
            get
            {
                if (Действующая_скидка >= 1)
                    return "red";
                else return null;
            }
        }

        public Nullable<decimal> NewPrice
        {
            get
            {
                
                if (Действующая_скидка > 1)
                    return Цена - (Цена * ((decimal)Действующая_скидка / 100));
                else return null;
            }
        }

    
        public virtual Катогория Катогория { get; set; }
        public virtual Поставщик Поставщик { get; set; }
        public virtual Производитель Производитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
